common: &COMMON
  env:
    HOME: /tmp # cargo needs it
  setup_script:
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y --profile=minimal --default-toolchain ${VERSION}-x86_64-unknown-freebsd
    - pkg install -y llvm
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  build_script:
    - . $HOME/.cargo/env
    - cargo build
  test_script:
    - . $HOME/.cargo/env
    - cargo test

task:
  env:
    VERSION: 1.77.0
  matrix:
    - name: FreeBSD 13.5 MSRV
      freebsd_instance:
        image: freebsd-13-5-release-amd64
    - name: FreeBSD 14.3 MSRV
      freebsd_instance:
        image: freebsd-14-3-release-amd64-ufs
    - name: FreeBSD 15.0-ALPHA4 MSRV
      freebsd_instance:
        image: freebsd-15-0-alpha4-amd64-ufs
  << : *COMMON
  before_cache_script: rm -rf $HOME/.cargo/registry/index

task:
  name: FreeBSD 14-3 nightly
  env:
    VERSION: nightly
  freebsd_instance:
    image: freebsd-14-3-release-amd64-ufs
  << : *COMMON
  clippy_script:
    - . $HOME/.cargo/env
    - rustup component add clippy
    - cargo clippy --all-targets -- -D warnings
  audit_script:
    # install ca_root_nss due to https://github.com/rustsec/rustsec/issues/1137
    - pkg install -y ca_root_nss cargo-audit
    - . $HOME/.cargo/env
    - cargo audit
  fmt_script:
    - . $HOME/.cargo/env
    - rustup component add rustfmt
    - cargo fmt --all -- --check --color=never
  minver_script:
    - . $HOME/.cargo/env
    - cargo update -Zdirect-minimal-versions
    - cargo check --all-targets
  before_cache_script: rm -rf $HOME/.cargo/registry/index
